#theme: jekyll-theme-hacker
#theme: jekyll-theme-merlot
#theme: jekyll-theme-midnight
#theme: jekyll-theme-minimal

#To use any other Jekyll theme hosted on GitHub, type remote_theme: THEME-NAME
remote_theme: jekyll-theme-minima
